<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shivaleela-H-MacBook-Pro.local" name="Script.STAAR_MaintDoc_SANITY_TEST" tests="2" failures="1" timestamp="11 Feb 2015 09:53:01 GMT" time="370.825" errors="0">
  <testcase name="Login" time="4.371" classname="Script.STAAR_MaintDoc_SANITY_TEST"/>
  <testcase name="getExcelData" time="366.454" classname="Script.STAAR_MaintDoc_SANITY_TEST">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Script.STAAR_MaintDoc_SANITY_TEST.VerifyProgramFunInfo(STAAR_MaintDoc_SANITY_TEST.java:132)
	at Script.STAAR_MaintDoc_SANITY_TEST.getExcelData(STAAR_MaintDoc_SANITY_TEST.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
]]>
    </failure>
  </testcase> <!-- getExcelData -->
</testsuite> <!-- Script.STAAR_MaintDoc_SANITY_TEST -->
